version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_HOST: postgres-db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      BITCOIN_RPC_USER: ${BITCOIN_RPC_USER}
      BITCOIN_RPC_PASSWORD: ${BITCOIN_RPC_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my_network

  ingestion:
    build:
      context: ./ingestion
    container_name: ingestion
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      BITCOIN_RPC_USER: ${BITCOIN_RPC_USER}
      BITCOIN_RPC_PASSWORD: ${BITCOIN_RPC_PASSWORD}
      BITCOIN_RPC_HOST: bitcoin-core
      BITCOIN_RPC_PORT: 8332
    depends_on:
      - postgres
      - bitcoin-core
    networks:
      - my_network

  bitcoin-core:
    image: ruimarinho/bitcoin-core:22
    ports:
      - "8332:8332"
    environment:
      BITCOIN_RPC_USER: ${BITCOIN_RPC_USER}
      BITCOIN_RPC_PASSWORD: ${BITCOIN_RPC_PASSWORD}
      BITCOIN_PORT: 8332
      BITCOIN_EXTRA_ARGS: |
        Prune=550
        txindex=0  
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin 
    expose:
      - 8332
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
  bitcoin_data: