name: CI/CD Pipeline for Bitcoin Explorer

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

concurrency:
  group: bitcoin-explorer-deployment
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/btc-explorer-backend:latest -f ./backend/Dockerfile ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/btc-explorer-backend:latest

      - name: Build and push frontend Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/btc-explorer-frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/btc-explorer-frontend:latest

      - name: Build and push ingestion Docker image
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/btc-explorer-ingestion:latest -f ./ingestion/Dockerfile ./ingestion
          docker push ${{ secrets.DOCKER_USERNAME }}/btc-explorer-ingestion:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: SSH Deploy Using Password
        run: |
          sshpass -p "${{ secrets.DEPLOY_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} <<EOF
            
            # Stop and remove specific containers to avoid conflicts
            docker stop btc-explorer-backend || true
            docker rm btc-explorer-backend || true
            docker stop btc-explorer-frontend || true
            docker rm btc-explorer-frontend || true
            docker stop btc-explorer-ingestion || true
            docker rm btc-explorer-ingestion || true
            docker network prune -f || true

            # Pull the latest images
            docker pull ${{ secrets.DOCKER_USERNAME }}/btc-explorer-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/btc-explorer-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/btc-explorer-ingestion:latest

            # Navigate to the project directory and start containers using docker-compose
            cd ~/Bitcoin-Explorer || exit 1
            docker-compose down
            docker-compose up -d
          EOF

      - name: Verify Deployment
        run: |
          sshpass -p "${{ secrets.DEPLOY_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} <<EOF
            # Check running containers and their images
            docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
          EOF
