name: CI/CD Pipeline for Bitcoin Explorer

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

concurrency:
  group: bitcoin-explorer-deployment
  cancel-in-progress: true

env:
  VERSION: v${{ github.run_number }}  # Using GitHub's run number as a version

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/btc-explorer-backend:${{ env.VERSION }} -f ./backend/Dockerfile ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/btc-explorer-backend:${{ env.VERSION }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/btc-explorer-frontend:${{ env.VERSION }} -f ./frontend/Dockerfile ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/btc-explorer-frontend:${{ env.VERSION }}

      - name: Build and push ingestion Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/btc-explorer-ingestion:${{ env.VERSION }} -f ./ingestion/Dockerfile ./ingestion
          docker push ${{ secrets.DOCKER_USERNAME }}/btc-explorer-ingestion:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: SSH Deploy Using Password
        run: |
          sshpass -p "${{ secrets.DEPLOY_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} <<EOF
            cd ~/Bitcoin-Explorer || exit 1

            sed -i 's|image: omkarvaity/btc-explorer-backend:.*|image: omkarvaity/btc-explorer-backend:${{ env.VERSION }}|' docker-compose.yml
            sed -i 's|image: omkarvaity/btc-explorer-frontend:.*|image: omkarvaity/btc-explorer-frontend:${{ env.VERSION }}|' docker-compose.yml
            sed -i 's|image: omkarvaity/btc-explorer-ingestion:.*|image: omkarvaity/btc-explorer-ingestion:${{ env.VERSION }}|' docker-compose.yml

            docker pull ${{ secrets.DOCKER_USERNAME }}/btc-explorer-backend:${{ env.VERSION }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/btc-explorer-frontend:${{ env.VERSION }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/btc-explorer-ingestion:${{ env.VERSION }}

            docker-compose down
            docker-compose up -d
          EOF

      - name: Verify Deployment
        run: |
          sshpass -p "${{ secrets.DEPLOY_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} <<EOF
            docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}"
          EOF
